//! Canonical static RON assets emitted by the content guest.
//!
//! 由 content guest 发射的 canonical 静态 RON 资产。

use anyhow::Result;
use souprune_vessel::prelude::*;

/// Emit all static canonical RON assets owned by this mod.
///
/// 发射当前 mod 拥有的全部静态 canonical RON 资产。
pub fn emit_all(reg: &mut Registry) -> Result<()> {
    reg.emit_canonical_source(
        "actors/items/basic.items.ron",
        include_str!("../ron/actors/items/basic.items.ron"),
    )?;
    reg.emit_canonical_source("app/flow.ron", include_str!("../ron/app/flow.ron"))?;
    reg.emit_canonical_source(
        "app/global.fre.ron",
        include_str!("../ron/app/global.fre.ron"),
    )?;
    reg.emit_canonical_source("app/input.ron", include_str!("../ron/app/input.ron"))?;
    reg.emit_canonical_source(
        "battle/common/end_view_interaction.sequence.ron",
        include_str!("../ron/battle/common/end_view_interaction.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/common/enemy_turn.sequence.ron",
        include_str!("../ron/battle/common/enemy_turn.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/common/fight_target.sequence.ron",
        include_str!("../ron/battle/common/fight_target.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/common/narration.sequence.ron",
        include_str!("../ron/battle/common/narration.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/common/player_turn.sequence.ron",
        include_str!("../ron/battle/common/player_turn.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/common/show_narration.sequence.ron",
        include_str!("../ron/battle/common/show_narration.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/mercy/end.sequence.ron",
        include_str!("../ron/battle/mercy/end.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/mercy/spare.sequence.ron",
        include_str!("../ron/battle/mercy/spare.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/players/player.battle_player.ron",
        include_str!("../ron/battle/players/player.battle_player.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/rules/dialogue_stop.fre.ron",
        include_str!("../ron/battle/rules/dialogue_stop.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/rules/dialogue_test.fre.ron",
        include_str!("../ron/battle/rules/dialogue_test.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/rules/fight_hit.fre.ron",
        include_str!("../ron/battle/rules/fight_hit.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/rules/menu_cancel.fre.ron",
        include_str!("../ron/battle/rules/menu_cancel.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/rules/menu_confirm.fre.ron",
        include_str!("../ron/battle/rules/menu_confirm.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/rules/menu_navigation.fre.ron",
        include_str!("../ron/battle/rules/menu_navigation.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/templates/undertale_battle.sequence.ron",
        include_str!("../ron/battle/templates/undertale_battle.sequence.ron"),
    )?;
    reg.emit_canonical_source(
        "battle/view/undertale.view.ron",
        include_str!("../ron/battle/view/undertale.view.ron"),
    )?;
    reg.emit_canonical_source(
        "narrative/dialogue.fre.ron",
        include_str!("../ron/narrative/dialogue.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "narrative/dialogue.ron",
        include_str!("../ron/narrative/dialogue.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/characters/frisk/animations.animation_config.ron",
        include_str!("../ron/overworld/characters/frisk/animations.animation_config.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/characters/frisk.character.ron",
        include_str!("../ron/overworld/characters/frisk.character.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/chase_config.ron",
        include_str!("../ron/overworld/chase_config.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/players/player_behavior.ron",
        include_str!("../ron/overworld/players/player_behavior.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/rules/backpack.fre.ron",
        include_str!("../ron/overworld/rules/backpack.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/rules/interaction.fre.ron",
        include_str!("../ron/overworld/rules/interaction.fre.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/view/damage_flash.view.ron",
        include_str!("../ron/overworld/view/damage_flash.view.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/view/dialogue.view.ron",
        include_str!("../ron/overworld/view/dialogue.view.ron"),
    )?;
    reg.emit_canonical_source(
        "overworld/view/undertale_backpack.view.ron",
        include_str!("../ron/overworld/view/undertale_backpack.view.ron"),
    )?;
    reg.emit_canonical_source(
        "view/structures/attack_bar.sdf.ron",
        include_str!("../ron/view/structures/attack_bar.sdf.ron"),
    )?;
    reg.emit_canonical_source(
        "view/structures/hp_bar.sdf.ron",
        include_str!("../ron/view/structures/hp_bar.sdf.ron"),
    )?;
    reg.emit_canonical_source(
        "view/structures/view_box.sdf.ron",
        include_str!("../ron/view/structures/view_box.sdf.ron"),
    )?;
    reg.emit_canonical_source(
        "view/touch_layout.ron",
        include_str!("../ron/view/touch_layout.ron"),
    )?;
    Ok(())
}
